/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PermataSenderFrame.java
 *
 * Created on May 20, 2009, 12:49:44 PM
 */

package com.xmlgateway.server.simulator;

import com.xmlgateway.server.configuration.ServerConfiguration;
import com.xmlgateway.server.helper.ISOMsgHelper;
import com.xmlgateway.server.helper.PackagerFactory;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.InputStream;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;
import org.jpos.iso.ISOException;
import org.jpos.iso.ISOMUX;
import org.jpos.iso.ISOMsg;
import org.jpos.iso.ISORequest;
import org.jpos.iso.channel.PostChannel;
import org.jpos.iso.packager.GenericPackager;

/**
 *
 * @author ifnu
 */
public class BankSenderFrame extends javax.swing.JFrame {
    private static final Log LOGGER = LogFactory.getLog(BankSenderFrame.class);
    private final PostChannel itmChannel;
    private final ISOMUX isomux;
    private MessageCreator permataMessageCreator = new BankMessageCreator();
    private ServerConfiguration conf;

    /** Creates new form PermataSenderFrame */
    public BankSenderFrame() throws FileNotFoundException, ISOException {
        initComponents();
        setLocationRelativeTo(null);
        conf = ServerConfiguration.getConfiguration("conf/server.xml");
        LOGGER.info("ITM @ " + conf.getServer().getIp() + ":" + conf.getServer().getPort());

        //connect to itm
        InputStream inputStream = new FileInputStream("conf/itm-iso-conf.xml");
        GenericPackager itmPackager = new GenericPackager(inputStream);
        itmChannel = new PostChannel(conf.getServer().getIp(),conf.getServer().getPort(),itmPackager);
        isomux = new ISOMUX(itmChannel){

            @Override
            protected String getKey(ISOMsg m) throws ISOException {
                return m.getString(11);
            }

        };
        new Thread(isomux).start();
        Date date = new Date();
        txtBit7.setText(new SimpleDateFormat("MMddHHmmss").format(date));
        String currTime =String.valueOf(System.currentTimeMillis());
        txtBit11.setText(currTime.substring(currTime.length()-6, currTime.length()));
        txtBit12.setText(new SimpleDateFormat("HHmmss").format(date));
        txtBit13.setText(new SimpleDateFormat("MMdd").format(date));
        txtBit15.setText(new SimpleDateFormat("MMdd").format(date));

        txt0200Bit7.setText(new SimpleDateFormat("MMddHHmmss").format(date));
        txt0200Bit11.setText(currTime.substring(currTime.length()-6, currTime.length()));
        txt0200Bit12.setText(new SimpleDateFormat("HHmmss").format(date));
        txt0200Bit13.setText(new SimpleDateFormat("MMdd").format(date));
        txt0200Bit15.setText(new SimpleDateFormat("MMdd").format(date));

        txt0400Bit7.setText(new SimpleDateFormat("MMddHHmmss").format(date));
        txt0400Bit11.setText(currTime.substring(currTime.length()-6, currTime.length()));
        txt0400Bit12.setText(new SimpleDateFormat("HHmmss").format(date));
        txt0400Bit13.setText(new SimpleDateFormat("MMdd").format(date));
        txt0400Bit15.setText(new SimpleDateFormat("MMdd").format(date));

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel38 = new javax.swing.JLabel();
        txt0200Bit2 = new javax.swing.JTextField();
        txt0200Bit3 = new javax.swing.JTextField();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        txt0200Bit4 = new javax.swing.JTextField();
        txt0200Bit7 = new javax.swing.JTextField();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        txt0200Bit11 = new javax.swing.JTextField();
        txt0200Bit12 = new javax.swing.JTextField();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        txt0200Bit13 = new javax.swing.JTextField();
        jLabel45 = new javax.swing.JLabel();
        jrb0200SetBit14 = new javax.swing.JRadioButton();
        jrb0200UnsetBit14 = new javax.swing.JRadioButton();
        txt0200Bit14 = new javax.swing.JTextField();
        txt0200Bit15 = new javax.swing.JTextField();
        jLabel46 = new javax.swing.JLabel();
        txt0200MSISDN = new javax.swing.JTextField();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        txt0200Bit63 = new javax.swing.JTextField();
        txt0200Bit61 = new javax.swing.JTextField();
        txt0200Bit49 = new javax.swing.JTextField();
        txt0200Bit48 = new javax.swing.JTextField();
        jrb0200SetBit41 = new javax.swing.JRadioButton();
        jrb0200UnsetBit41 = new javax.swing.JRadioButton();
        txt0200Bit41 = new javax.swing.JTextField();
        txt0200Bit37 = new javax.swing.JTextField();
        txt0200Bit32 = new javax.swing.JTextField();
        txt0200Bit18 = new javax.swing.JTextField();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        btnSendInquiry = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        txt0200Message = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtBit4 = new javax.swing.JTextField();
        txtBit103 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtMessage = new javax.swing.JTextArea();
        btnSend = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtBit2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cmbBit3 = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        txtBit7 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtBit11 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtBit12 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        txtBit13 = new javax.swing.JTextField();
        txtBit15 = new javax.swing.JTextField();
        txtBit22 = new javax.swing.JTextField();
        txtBit26 = new javax.swing.JTextField();
        txtBit32 = new javax.swing.JTextField();
        txtBit33 = new javax.swing.JTextField();
        txtBit37 = new javax.swing.JTextField();
        txtBit41 = new javax.swing.JTextField();
        txtBit43 = new javax.swing.JTextField();
        cmbBit18 = new javax.swing.JComboBox();
        txtBit49 = new javax.swing.JTextField();
        txtBit61 = new javax.swing.JTextField();
        cmbBit47 = new javax.swing.JComboBox();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtMessageReversal = new javax.swing.JTextArea();
        btnSendReversal = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtMessageReversal1 = new javax.swing.JTextArea();
        btnSendReversal1 = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        jrb0400SetBit14 = new javax.swing.JRadioButton();
        jrb0400UnsetBit14 = new javax.swing.JRadioButton();
        txt0400Bit14 = new javax.swing.JTextField();
        txt0400Bit15 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        txt0400Bit13 = new javax.swing.JTextField();
        txt0400Bit12 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        txt0400Bit11 = new javax.swing.JTextField();
        txt0400Bit7 = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        txt0400Bit4 = new javax.swing.JTextField();
        txt0400Bit3 = new javax.swing.JTextField();
        txt0400Bit2 = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        txt0400Bit18 = new javax.swing.JTextField();
        txt0400Bit32 = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        txt0400Bit37 = new javax.swing.JTextField();
        jrb0400SetBit41 = new javax.swing.JRadioButton();
        jrb0400UnsetBit41 = new javax.swing.JRadioButton();
        txt0400Bit48 = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        txt0400MSISDN = new javax.swing.JTextField();
        txt0400Bit63 = new javax.swing.JTextField();
        txt0400Bit61 = new javax.swing.JTextField();
        txt0400Bit49 = new javax.swing.JTextField();
        txt0400Bit41 = new javax.swing.JTextField();
        jLabel57 = new javax.swing.JLabel();
        txt0400Bit90 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel38.setText("Primary Account Number (2)");

        txt0200Bit2.setText("00");

        txt0200Bit3.setText("180000");

        jLabel39.setText("Processing Code (3)");

        jLabel40.setText("Amount Transaction (4)");

        txt0200Bit4.setText("100000");

        jLabel41.setText("Transmission Date (7)");

        jLabel42.setText("System Trace Number (11)");

        txt0200Bit11.setText("123456");

        jLabel43.setText("Time, Local Transaction (12)");

        jLabel44.setText("Date, Local Transaction (13)");

        jLabel45.setText("Date, Expire (14)");

        jrb0200SetBit14.setSelected(true);
        jrb0200SetBit14.setText("Set");

        jrb0200UnsetBit14.setText("Unset");

        jLabel46.setText("Date, Settlement (15)");

        txt0200MSISDN.setText("081908988978");

        jLabel48.setText("Mobile Number (103)");

        jLabel49.setText("Institution ID Code (63)");

        txt0200Bit63.setText("110");

        txt0200Bit61.setText("101090010009");

        txt0200Bit49.setText("360");

        jrb0200SetBit41.setSelected(true);
        jrb0200SetBit41.setText("Set");

        jrb0200UnsetBit41.setText("Unset");

        txt0200Bit41.setText("00010981");

        txt0200Bit37.setText("000000007093");

        txt0200Bit32.setText("13");

        txt0200Bit18.setText("6011");

        jLabel50.setText("Merchant's Type (18)");

        jLabel51.setText("Acquiring Institution Identification Code (32)");

        jLabel52.setText("Retrieval Reference Number (37)");

        jLabel53.setText("Card Acceptor Terminal (41)");

        jLabel54.setText("Additional Data (48)");

        jLabel55.setText("Currency, Transaction (49)");

        jLabel56.setText("Reserved,  Used as POS Data (61)");

        btnSendInquiry.setText("Send");
        btnSendInquiry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendInquiryActionPerformed(evt);
            }
        });

        txt0200Message.setColumns(20);
        txt0200Message.setRows(5);
        jScrollPane3.setViewportView(txt0200Message);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSendInquiry)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel38)
                                    .addComponent(jLabel40)
                                    .addComponent(jLabel39))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt0200Bit4, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt0200Bit3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt0200Bit2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel45)
                                    .addComponent(jLabel44)
                                    .addComponent(jLabel43)
                                    .addComponent(jLabel42)
                                    .addComponent(jLabel41)
                                    .addComponent(jLabel46))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt0200Bit7, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt0200Bit11, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 186, Short.MAX_VALUE)
                                .addComponent(txt0200Bit15, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(186, 186, 186)
                                .addComponent(jrb0200SetBit14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jrb0200UnsetBit14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt0200Bit14, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(186, 186, 186)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txt0200Bit13, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt0200Bit12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 116, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel51)
                            .addComponent(jLabel54)
                            .addComponent(jLabel50)
                            .addComponent(jLabel52, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel53)
                            .addComponent(jLabel55)
                            .addComponent(jLabel56)
                            .addComponent(jLabel49)
                            .addComponent(jLabel48))
                        .addGap(56, 56, 56)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt0200MSISDN, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt0200Bit63, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt0200Bit37, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt0200Bit18, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt0200Bit49, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt0200Bit61, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jrb0200SetBit41)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jrb0200UnsetBit41)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt0200Bit41, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txt0200Bit48, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt0200Bit32, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(59, 59, 59)))
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 1071, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel38)
                            .addComponent(txt0200Bit2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(jLabel39))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt0200Bit3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel40)
                                    .addComponent(txt0200Bit4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel52)))
                        .addGap(41, 41, 41)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel41)
                            .addComponent(txt0200Bit7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel42)
                            .addComponent(txt0200Bit11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel43)
                            .addComponent(txt0200Bit12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt0200Bit18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel50))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel51)
                            .addComponent(txt0200Bit32, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt0200Bit37, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jrb0200SetBit41)
                            .addComponent(jrb0200UnsetBit41)
                            .addComponent(txt0200Bit41, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel53))
                        .addGap(6, 6, 6)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jLabel54))
                            .addComponent(txt0200Bit48, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt0200Bit49, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel55))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt0200Bit61, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel56))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt0200Bit63, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel49))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel44)
                    .addComponent(txt0200Bit13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt0200MSISDN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel48))
                .addGap(9, 9, 9)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel45)
                    .addComponent(txt0200Bit14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jrb0200SetBit14)
                    .addComponent(jrb0200UnsetBit14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt0200Bit15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel46))
                .addGap(18, 18, 18)
                .addComponent(btnSendInquiry)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Transaction Inquiry (0200)", jPanel3);

        jLabel1.setText("Amount Transaction (4)");

        jLabel2.setText("Mobile Number (103)");

        txtBit4.setText("100000");

        txtBit103.setText("081908988978");

        txtMessage.setColumns(20);
        txtMessage.setRows(5);
        jScrollPane1.setViewportView(txtMessage);

        btnSend.setText("Send");
        btnSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendActionPerformed(evt);
            }
        });

        jLabel3.setText("Primary Account Number (2)");

        txtBit2.setText("00");

        jLabel4.setText("Processing Code (3)");

        cmbBit3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "320000", "550000", "800000", "530000", "560000" }));

        jLabel5.setText("Transmission Date (7,MMDDhhmmss)");

        jLabel6.setText("System Trace Number (11)");

        txtBit11.setText("123456");

        jLabel7.setText("Time, Local Transaction (12)");

        jLabel8.setText("Date, Local Transaction (13)");

        jLabel9.setText("Date, Settlement (15)");

        jLabel10.setText("Merchant's Type (18)");

        jLabel11.setText("Point Of Entry Mode (22)");

        jLabel12.setText("Point Of Service Pin Capture Mode (26)");

        jLabel13.setText("Acquiring Institution Identification Code (32)");

        jLabel14.setText("Forwarding Institution Identification Code (33)");

        jLabel15.setText("Retrieval Reference Number (37)");

        jLabel16.setText("Card Acceptor Terminal (41)");

        jLabel17.setText("Card Acceptor Name And Location (43)");

        jLabel18.setText("Payment Code (47)");

        jLabel19.setText("Currency, Transaction (49)");

        jLabel20.setText("Reserved,  Used as POS Data (61)");

        txtBit22.setText("000");

        txtBit26.setText("12");

        txtBit32.setText("13");

        txtBit33.setText("13");

        txtBit37.setText("000000007093");

        txtBit41.setText("00010981");

        txtBit43.setText("PERMATABANK INDONESIA  mataMobile");

        cmbBit18.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "6010", "6011", "6012", "6013", "6014", "6015" }));
        cmbBit18.setSelectedIndex(1);

        txtBit49.setText("360");

        txtBit61.setText("101090010009");

        cmbBit47.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "HUT", "AXS", "SAT", "TLK", "IMT", "EBT", "M8T", "EXL" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4)
                    .addComponent(jLabel9)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel8)
                    .addComponent(jLabel11)
                    .addComponent(jLabel10)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtBit12, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBit4, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBit2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbBit3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBit7, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBit11, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBit13, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                    .addComponent(txtBit15, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                    .addComponent(cmbBit18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBit22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 166, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addGap(223, 223, 223))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 148, Short.MAX_VALUE))
                    .addComponent(jLabel14)
                    .addComponent(jLabel15)
                    .addComponent(jLabel17)
                    .addComponent(jLabel16)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(257, 257, 257))
                    .addComponent(jLabel20))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtBit43, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtBit41, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtBit37, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtBit26, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtBit49, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtBit103, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtBit32, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtBit33, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtBit61, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(cmbBit47, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnSend)
                .addContainerGap(1012, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1071, Short.MAX_VALUE)
                .addGap(43, 43, 43))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(txtBit26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(txtBit32, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBit33, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBit37, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtBit7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel15))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addGap(17, 17, 17)
                                    .addComponent(jLabel4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jLabel1))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(txtBit2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(cmbBit3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel14)
                                        .addComponent(txtBit4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGap(32, 32, 32))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtBit11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(7, 7, 7)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtBit12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtBit13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtBit15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(24, 24, 24)
                                .addComponent(jLabel9))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jLabel16))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(txtBit41, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17)
                            .addComponent(txtBit43, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(cmbBit47, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(txtBit49, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbBit18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addGap(7, 7, 7)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(txtBit22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel20)
                            .addComponent(txtBit61, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(txtBit103, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSend)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(89, 89, 89))
        );

        jTabbedPane1.addTab("Transaction/Registration Request (0200)", jPanel1);

        txtMessageReversal.setColumns(20);
        txtMessageReversal.setRows(5);
        jScrollPane2.setViewportView(txtMessageReversal);

        btnSendReversal.setText("Send");
        btnSendReversal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendReversalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(btnSendReversal)
                .addContainerGap(985, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(6, 6, 6)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1081, Short.MAX_VALUE)
                    .addGap(6, 6, 6)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(btnSendReversal)
                .addContainerGap(553, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(78, 78, 78)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 492, Short.MAX_VALUE)
                    .addGap(43, 43, 43)))
        );

        jTabbedPane1.addTab("Transaction Reversal Request (0420)", jPanel2);

        txtMessageReversal1.setColumns(20);
        txtMessageReversal1.setRows(5);
        jScrollPane4.setViewportView(txtMessageReversal1);

        btnSendReversal1.setText("Send");
        btnSendReversal1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendReversal1ActionPerformed(evt);
            }
        });

        jLabel24.setText("Date, Expire (14)");

        jrb0400SetBit14.setText("Set");

        jrb0400UnsetBit14.setText("Unset");

        jLabel21.setText("Date, Settlement (15)");

        jLabel22.setText("Date, Local Transaction (13)");

        jLabel23.setText("Time, Local Transaction (12)");

        jLabel25.setText("System Trace Number (11)");

        txt0400Bit11.setText("123456");

        jLabel26.setText("Transmission Date (7)");

        txt0400Bit4.setText("100000");

        txt0400Bit3.setText("180000");

        txt0400Bit2.setText("00");

        jLabel27.setText("Primary Account Number (2)");

        jLabel28.setText("Processing Code (3)");

        jLabel29.setText("Amount Transaction (4)");

        jLabel30.setText("Merchant's Type (18)");

        txt0400Bit18.setText("6011");

        txt0400Bit32.setText("13");

        jLabel31.setText("Acquiring Institution Identification Code (32)");

        jLabel32.setText("Retrieval Reference Number (37)");

        txt0400Bit37.setText("000000007093");

        jrb0400SetBit41.setText("Set");

        jrb0400UnsetBit41.setText("Unset");

        jLabel33.setText("Card Acceptor Terminal (41)");

        jLabel34.setText("Additional Data (48)");

        jLabel35.setText("Currency, Transaction (49)");

        jLabel36.setText("Reserved,  Used as POS Data (61)");

        jLabel37.setText("Institution ID Code (63)");

        jLabel47.setText("Mobile Number (103)");

        txt0400MSISDN.setText("081908988978");

        txt0400Bit63.setText("110");
        txt0400Bit63.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt0400Bit63KeyReleased(evt);
            }
        });

        txt0400Bit61.setText("101090010009");

        txt0400Bit49.setText("360");

        txt0400Bit41.setText("00010981");

        jLabel57.setText("Original Payment Data (90)");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSendReversal1)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel27)
                                            .addComponent(jLabel29)
                                            .addComponent(jLabel28))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txt0400Bit4, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txt0400Bit3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txt0400Bit2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel24)
                                            .addComponent(jLabel22)
                                            .addComponent(jLabel23)
                                            .addComponent(jLabel25)
                                            .addComponent(jLabel26)
                                            .addComponent(jLabel21))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txt0400Bit7, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txt0400Bit11, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 186, Short.MAX_VALUE)
                                        .addComponent(txt0400Bit15, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGap(186, 186, 186)
                                        .addComponent(jrb0400SetBit14)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jrb0400UnsetBit14)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txt0400Bit14, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGap(186, 186, 186)
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(txt0400Bit13, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txt0400Bit12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 116, Short.MAX_VALUE)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel31)
                                    .addComponent(jLabel34)
                                    .addComponent(jLabel30)
                                    .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel33)
                                    .addComponent(jLabel35)
                                    .addComponent(jLabel36)
                                    .addComponent(jLabel37)
                                    .addComponent(jLabel47)
                                    .addComponent(jLabel57))
                                .addGap(56, 56, 56)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt0400MSISDN, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt0400Bit63, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt0400Bit37, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt0400Bit32, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt0400Bit18, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt0400Bit49, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt0400Bit61, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jrb0400SetBit41)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jrb0400UnsetBit41)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txt0400Bit41, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txt0400Bit48, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt0400Bit90, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(17, 17, 17))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 1081, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel27)
                            .addComponent(txt0400Bit2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(jLabel28))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt0400Bit3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel29)
                                    .addComponent(txt0400Bit4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel32)))
                        .addGap(41, 41, 41)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel26)
                            .addComponent(txt0400Bit7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel25)
                            .addComponent(txt0400Bit11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel23)
                            .addComponent(txt0400Bit12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt0400Bit18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel30))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel31)
                            .addComponent(txt0400Bit32, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt0400Bit37, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jrb0400SetBit41)
                            .addComponent(jrb0400UnsetBit41)
                            .addComponent(txt0400Bit41, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel33))
                        .addGap(6, 6, 6)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jLabel34))
                            .addComponent(txt0400Bit48, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt0400Bit49, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel35))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt0400Bit61, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel36))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt0400Bit63, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel37))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(txt0400Bit13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt0400MSISDN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel47))
                .addGap(9, 9, 9)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(txt0400Bit14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jrb0400SetBit14)
                    .addComponent(jrb0400UnsetBit14)
                    .addComponent(jLabel57)
                    .addComponent(txt0400Bit90, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt0400Bit15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21))
                .addGap(18, 18, 18)
                .addComponent(btnSendReversal1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Transaction Reversal Request (0400)", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 659, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSendReversalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendReversalActionPerformed
        txtMessageReversal.setText("");
        ISOMsg permataMsg = permataMessageCreator.create0400();
        permataMsg.setPackager(PackagerFactory.getPermataPackager());
        txtMessageReversal.setText("Sending Message  : " + ISOMsgHelper.isoMsgToString(permataMsg) + "\n");
        ISORequest r = new ISORequest(permataMsg);
        isomux.queue(r);
        ISOMsg reply = r.getResponse(30);
        if(reply!=null){
            txtMessageReversal.setText("Sending Message  : " + ISOMsgHelper.isoMsgToString(permataMsg) + "\n" + "Recieving Message : " + ISOMsgHelper.isoMsgToString(reply));
        } else {
            txtMessageReversal.setText(txtMessageReversal.getText() + "\n" + "tidak ada response sampai timeout" );
        }
}//GEN-LAST:event_btnSendReversalActionPerformed

    private void btnSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendActionPerformed
        try {
            txtMessage.setText("");
            ISOMsg permataMsg = new ISOMsg();
            permataMsg.setMTI("0200");
            permataMsg.set(2, txtBit2.getText());
            permataMsg.set(3, (String) cmbBit3.getSelectedItem());
            permataMsg.set(4, ISOMsgHelper.padZeroRightAlign(txtBit4.getText(),12));
            permataMsg.set(7, txtBit7.getText());
            String currTime =String.valueOf(System.currentTimeMillis());
            txtBit11.setText(currTime.substring(currTime.length()-6, currTime.length()));
            permataMsg.set(11, txtBit11.getText());
            permataMsg.set(12, txtBit12.getText());
            permataMsg.set(13, txtBit13.getText());
            permataMsg.set(15, txtBit15.getText());
            permataMsg.set(18, cmbBit18.getSelectedItem().toString());
            permataMsg.set(22, txtBit22.getText());
            permataMsg.set(26, txtBit26.getText());
            permataMsg.set(32, txtBit32.getText());
            permataMsg.set(33, txtBit33.getText());
            permataMsg.set(37, txtBit37.getText());
            permataMsg.set(41, txtBit41.getText());
            permataMsg.set(43, ISOMsgHelper.padSpaceLeftAlign(txtBit43.getText(),40));
            permataMsg.set(47, cmbBit47.getSelectedItem().toString());
            permataMsg.set(49, txtBit49.getText());
            permataMsg.set(61, txtBit61.getText());
            permataMsg.set(103, txtBit103.getText());
            permataMsg.setPackager(PackagerFactory.getPermataPackager());
            txtMessage.setText("Sending Message  : " + ISOMsgHelper.isoMsgToString(permataMsg) + "\n");
            ISORequest r = new ISORequest(permataMsg);
            isomux.queue(r);
            ISOMsg reply = r.getResponse(conf.getServer().getTimeout());
            if (reply != null) {
                txtMessage.setText("Sending Message  : " + ISOMsgHelper.isoMsgToString(permataMsg) + "\n" + "Recieving Message : " + ISOMsgHelper.isoMsgToString(reply));
            } else {
                txtMessage.setText(txtMessage.getText() + "\n" + "tidak ada response sampai timeout");
            }
        } catch (ISOException ex) {
            Logger.getLogger(BankSenderFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
}//GEN-LAST:event_btnSendActionPerformed

    private void btnSendInquiryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendInquiryActionPerformed
        try {
            // TODO add your handling code here:
            txt0200Message.setText("");
            ISOMsg permataMsg = new ISOMsg();
            permataMsg.setMTI("0200");
            permataMsg.set(2, txt0200Bit2.getText());
            permataMsg.set(3, txt0200Bit3.getText());
            permataMsg.set(4, ISOMsgHelper.padZeroRightAlign(txt0200Bit4.getText(), 12));
            permataMsg.set(7, txt0200Bit7.getText());
            String currTime = String.valueOf(System.currentTimeMillis());
            txt0200Bit11.setText(currTime.substring(currTime.length() - 6, currTime.length()));
            permataMsg.set(11, txt0200Bit11.getText());
            permataMsg.set(12, txt0200Bit12.getText());
            permataMsg.set(13, txt0200Bit13.getText());
            permataMsg.set(15, txt0200Bit15.getText());
            permataMsg.set(18, txt0200Bit18.getText());
//            permataMsg.set(22, txt0200Bit22.getText());
//            permataMsg.set(26, txt0200Bit26.getText());
            permataMsg.set(32, txt0200Bit32.getText());
//            permataMsg.set(33, txt0200Bit33.getText());
            permataMsg.set(37, txt0200Bit37.getText());
            permataMsg.set(41, txt0200Bit41.getText());
//            permataMsg.set(43, ISOMsgHelper.padSpaceLeftAlign(txt0200Bit43.getText(), 40));
//            permataMsg.set(47, cmb0200Bit47.getSelectedItem().toString());
            permataMsg.set(49, txt0200Bit49.getText());
            permataMsg.set(61, txt0200Bit61.getText());
            permataMsg.set(103, txt0200MSISDN.getText());
            permataMsg.setPackager(PackagerFactory.getPermataPackager());
            txt0200Message.setText("Sending Message  : " + ISOMsgHelper.isoMsgToString(permataMsg) + "\n");
            ISORequest r = new ISORequest(permataMsg);
            isomux.queue(r);
            ISOMsg reply = r.getResponse(conf.getServer().getTimeout());
            if (reply != null) {
                txt0200Message.setText("Sending Message  : " + ISOMsgHelper.isoMsgToString(permataMsg) + "\n" + "Recieving Message : " + ISOMsgHelper.isoMsgToString(reply));
            } else {
                txt0200Message.setText(txtMessage.getText() + "\n" + "tidak ada response sampai timeout");
            }
        } catch (ISOException ex) {
            Logger.getLogger(BankSenderFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
}//GEN-LAST:event_btnSendInquiryActionPerformed

    private void btnSendReversal1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendReversal1ActionPerformed
        // TODO add your handling code here:
        try{
            txtMessageReversal.setText("");
            ISOMsg axisMsg = new ISOMsg();
            axisMsg.setMTI("0400");
            axisMsg.set(2, txt0400Bit2.getText());
            axisMsg.set(3, txt0400Bit3.getText());
            axisMsg.set(4, ISOMsgHelper.padZeroRightAlign(txt0400Bit4.getText(),12));
            axisMsg.set(7, txt0400Bit7.getText());
            axisMsg.set(11, txt0400Bit11.getText());
            axisMsg.set(12, txt0400Bit12.getText());
            axisMsg.set(13, txt0400Bit13.getText());
            if(jrb0400SetBit14.isSelected()){
                axisMsg.set(14,txt0400Bit14.getText());
            }
            axisMsg.set(15, txt0400Bit15.getText());
            axisMsg.set(18, txt0400Bit18.getText());
            axisMsg.set(32, txt0400Bit32.getText());
            axisMsg.set(37, txt0400Bit37.getText());
            if(jrb0400SetBit41.isSelected()){
                axisMsg.set(41, ISOMsgHelper.padZeroRightAlign(txtBit41.getText(),15));
            }
            axisMsg.set(48, txt0400Bit48.getText());
            axisMsg.set(49, txt0400Bit49.getText());
            axisMsg.set(61, txt0400Bit61.getText());
            axisMsg.set(63, txt0400Bit63.getText());
            axisMsg.set(90, txt0400Bit90.getText());
//            axisMsg.setPackager(axisWithoutYearPackager);
//            txtMessage.setText("Sending Message  : " + ISOMsgHelper.isoMsgToString(axisMsg) + "\n");
//            msg0200 = axisMsg;
//            ISORequest r = new ISORequest(axisMsg);
//            isomuxAxisWithoutYear.queue(r);
//            ISOMsg reply = r.getResponse(PropertiesDataFactory.getAxisTimeOut());
//            if (reply != null) {
//                txtMessageReversal.setText("Sending Message  : " + ISOMsgHelper.isoMsgToString(axisMsg) + "\n" + "Recieving Message : " + ISOMsgHelper.isoMsgToString(reply));
//            } else {
                txtMessageReversal.setText(txtMessage.getText() + "\n" + "tidak ada response sampai timeout");
//            }

        } catch (Exception ex) {
            Logger.getLogger(HutSenderFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
}//GEN-LAST:event_btnSendReversal1ActionPerformed

    private void txt0400Bit63KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt0400Bit63KeyReleased
        // TODO add your handling code here:
}//GEN-LAST:event_txt0400Bit63KeyReleased

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new BankSenderFrame().setVisible(true);
                } catch (FileNotFoundException ex) {
                    Logger.getLogger(BankSenderFrame.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ISOException ex) {
                    Logger.getLogger(BankSenderFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSend;
    private javax.swing.JButton btnSendInquiry;
    private javax.swing.JButton btnSendReversal;
    private javax.swing.JButton btnSendReversal1;
    private javax.swing.JComboBox cmbBit18;
    private javax.swing.JComboBox cmbBit3;
    private javax.swing.JComboBox cmbBit47;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JRadioButton jrb0200SetBit14;
    private javax.swing.JRadioButton jrb0200SetBit41;
    private javax.swing.JRadioButton jrb0200UnsetBit14;
    private javax.swing.JRadioButton jrb0200UnsetBit41;
    private javax.swing.JRadioButton jrb0400SetBit14;
    private javax.swing.JRadioButton jrb0400SetBit41;
    private javax.swing.JRadioButton jrb0400UnsetBit14;
    private javax.swing.JRadioButton jrb0400UnsetBit41;
    private javax.swing.JTextField txt0200Bit11;
    private javax.swing.JTextField txt0200Bit12;
    private javax.swing.JTextField txt0200Bit13;
    private javax.swing.JTextField txt0200Bit14;
    private javax.swing.JTextField txt0200Bit15;
    private javax.swing.JTextField txt0200Bit18;
    private javax.swing.JTextField txt0200Bit2;
    private javax.swing.JTextField txt0200Bit3;
    private javax.swing.JTextField txt0200Bit32;
    private javax.swing.JTextField txt0200Bit37;
    private javax.swing.JTextField txt0200Bit4;
    private javax.swing.JTextField txt0200Bit41;
    private javax.swing.JTextField txt0200Bit48;
    private javax.swing.JTextField txt0200Bit49;
    private javax.swing.JTextField txt0200Bit61;
    private javax.swing.JTextField txt0200Bit63;
    private javax.swing.JTextField txt0200Bit7;
    private javax.swing.JTextField txt0200MSISDN;
    private javax.swing.JTextArea txt0200Message;
    private javax.swing.JTextField txt0400Bit11;
    private javax.swing.JTextField txt0400Bit12;
    private javax.swing.JTextField txt0400Bit13;
    private javax.swing.JTextField txt0400Bit14;
    private javax.swing.JTextField txt0400Bit15;
    private javax.swing.JTextField txt0400Bit18;
    private javax.swing.JTextField txt0400Bit2;
    private javax.swing.JTextField txt0400Bit3;
    private javax.swing.JTextField txt0400Bit32;
    private javax.swing.JTextField txt0400Bit37;
    private javax.swing.JTextField txt0400Bit4;
    private javax.swing.JTextField txt0400Bit41;
    private javax.swing.JTextField txt0400Bit48;
    private javax.swing.JTextField txt0400Bit49;
    private javax.swing.JTextField txt0400Bit61;
    private javax.swing.JTextField txt0400Bit63;
    private javax.swing.JTextField txt0400Bit7;
    private javax.swing.JTextField txt0400Bit90;
    private javax.swing.JTextField txt0400MSISDN;
    private javax.swing.JTextField txtBit103;
    private javax.swing.JTextField txtBit11;
    private javax.swing.JTextField txtBit12;
    private javax.swing.JTextField txtBit13;
    private javax.swing.JTextField txtBit15;
    private javax.swing.JTextField txtBit2;
    private javax.swing.JTextField txtBit22;
    private javax.swing.JTextField txtBit26;
    private javax.swing.JTextField txtBit32;
    private javax.swing.JTextField txtBit33;
    private javax.swing.JTextField txtBit37;
    private javax.swing.JTextField txtBit4;
    private javax.swing.JTextField txtBit41;
    private javax.swing.JTextField txtBit43;
    private javax.swing.JTextField txtBit49;
    private javax.swing.JTextField txtBit61;
    private javax.swing.JTextField txtBit7;
    private javax.swing.JTextArea txtMessage;
    private javax.swing.JTextArea txtMessageReversal;
    private javax.swing.JTextArea txtMessageReversal1;
    // End of variables declaration//GEN-END:variables

}
